In [11]:
from transformers.pipelines import SUPPORTED_TASKS

/home/wjc/miniconda3/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
from pprint import pprint
pprint(SUPPORTED_TASKS.keys())

dict_keys(['audio-classification', 'automatic-speech-recognition', 'text-to-audio', 'feature-extraction', 'text-classification', 'token-classification', 'question-answering', 'table-question-answering', 'visual-question-answering', 'document-question-answering', 'fill-mask', 'summarization', 'translation', 'text2text-generation', 'text-generation', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-audio-classification', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-to-text', 'object-detection', 'zero-shot-object-detection', 'depth-estimation', 'video-classification', 'mask-generation', 'image-to-image'])

In [4]:
for k,v in SUPPORTED_TASKS.items():
    print(k)
    print(v)

audio-classification
{'impl': <class 'transformers.pipelines.audio_classification.AudioClassificationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForAudioClassification'>,), 'default': {'model': {'pt': ('superb/wav2vec2-base-superb-ks', '372e048')}}, 'type': 'audio'}
automatic-speech-recognition
{'impl': <class 'transformers.pipelines.automatic_speech_recognition.AutomaticSpeechRecognitionPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForCTC'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSpeechSeq2Seq'>), 'default': {'model': {'pt': ('facebook/wav2vec2-base-960h', '55bb623')}}, 'type': 'multimodal'}
text-to-audio
{'impl': <class 'transformers.pipelines.text_to_audio.TextToAudioPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForTextToWaveform'>, <class 'transformers.models.auto.modeling_auto.AutoModelForTextToSpectrogram'>), 'default': {'model': {'pt': ('suno/bark-small', '645cfba')}}, 'type': 'text'}
feature-extraction
{'impl': <class 'transformers.pipelines.feature_extraction.FeatureExtractionPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModel'>,), 'default': {'model': {'pt': ('distilbert/distilbert-base-cased', '935ac13'), 'tf': ('distilbert/distilbert-base-cased', '935ac13')}}, 'type': 'multimodal'}
text-classification
{'impl': <class 'transformers.pipelines.text_classification.TextClassificationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForSequenceClassification'>,), 'default': {'model': {'pt': ('distilbert/distilbert-base-uncased-finetuned-sst-2-english', 'af0f99b'), 'tf': ('distilbert/distilbert-base-uncased-finetuned-sst-2-english', 'af0f99b')}}, 'type': 'text'}
token-classification
{'impl': <class 'transformers.pipelines.token_classification.TokenClassificationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForTokenClassification'>,), 'default': {'model': {'pt': ('dbmdz/bert-large-cased-finetuned-conll03-english', 'f2482bf'), 'tf': ('dbmdz/bert-large-cased-finetuned-conll03-english', 'f2482bf')}}, 'type': 'text'}
question-answering
{'impl': <class 'transformers.pipelines.question_answering.QuestionAnsweringPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForQuestionAnswering'>,), 'default': {'model': {'pt': ('distilbert/distilbert-base-cased-distilled-squad', '626af31'), 'tf': ('distilbert/distilbert-base-cased-distilled-squad', '626af31')}}, 'type': 'text'}
table-question-answering
{'impl': <class 'transformers.pipelines.table_question_answering.TableQuestionAnsweringPipeline'>, 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForTableQuestionAnswering'>,), 'tf': (), 'default': {'model': {'pt': ('google/tapas-base-finetuned-wtq', '69ceee2'), 'tf': ('google/tapas-base-finetuned-wtq', '69ceee2')}}, 'type': 'text'}
visual-question-answering
{'impl': <class 'transformers.pipelines.visual_question_answering.VisualQuestionAnsweringPipeline'>, 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForVisualQuestionAnswering'>,), 'tf': (), 'default': {'model': {'pt': ('dandelin/vilt-b32-finetuned-vqa', '4355f59')}}, 'type': 'multimodal'}
document-question-answering
{'impl': <class 'transformers.pipelines.document_question_answering.DocumentQuestionAnsweringPipeline'>, 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForDocumentQuestionAnswering'>,), 'tf': (), 'default': {'model': {'pt': ('impira/layoutlm-document-qa', '52e01b3')}}, 'type': 'multimodal'}
fill-mask
{'impl': <class 'transformers.pipelines.fill_mask.FillMaskPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForMaskedLM'>,), 'default': {'model': {'pt': ('distilbert/distilroberta-base', 'ec58a5b'), 'tf': ('distilbert/distilroberta-base', 'ec58a5b')}}, 'type': 'text'}
summarization
{'impl': <class 'transformers.pipelines.text2text_generation.SummarizationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForSeq2SeqLM'>,), 'default': {'model': {'pt': ('sshleifer/distilbart-cnn-12-6', 'a4f8f3e'), 'tf': ('google-t5/t5-small', 'd769bba')}}, 'type': 'text'}
translation
{'impl': <class 'transformers.pipelines.text2text_generation.TranslationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForSeq2SeqLM'>,), 'default': {('en', 'fr'): {'model': {'pt': ('google-t5/t5-base', '686f1db'), 'tf': ('google-t5/t5-base', '686f1db')}}, ('en', 'de'): {'model': {'pt': ('google-t5/t5-base', '686f1db'), 'tf': ('google-t5/t5-base', '686f1db')}}, ('en', 'ro'): {'model': {'pt': ('google-t5/t5-base', '686f1db'), 'tf': ('google-t5/t5-base', '686f1db')}}}, 'type': 'text'}
text2text-generation
{'impl': <class 'transformers.pipelines.text2text_generation.Text2TextGenerationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForSeq2SeqLM'>,), 'default': {'model': {'pt': ('google-t5/t5-base', '686f1db'), 'tf': ('google-t5/t5-base', '686f1db')}}, 'type': 'text'}
text-generation
{'impl': <class 'transformers.pipelines.text_generation.TextGenerationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>,), 'default': {'model': {'pt': ('openai-community/gpt2', '6c0e608'), 'tf': ('openai-community/gpt2', '6c0e608')}}, 'type': 'text'}
zero-shot-classification
{'impl': <class 'transformers.pipelines.zero_shot_classification.ZeroShotClassificationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForSequenceClassification'>,), 'default': {'model': {'pt': ('facebook/bart-large-mnli', 'c626438'), 'tf': ('FacebookAI/roberta-large-mnli', '130fb28')}, 'config': {'pt': ('facebook/bart-large-mnli', 'c626438'), 'tf': ('FacebookAI/roberta-large-mnli', '130fb28')}}, 'type': 'text'}
zero-shot-image-classification
{'impl': <class 'transformers.pipelines.zero_shot_image_classification.ZeroShotImageClassificationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForZeroShotImageClassification'>,), 'default': {'model': {'pt': ('openai/clip-vit-base-patch32', 'f4881ba'), 'tf': ('openai/clip-vit-base-patch32', 'f4881ba')}}, 'type': 'multimodal'}
zero-shot-audio-classification
{'impl': <class 'transformers.pipelines.zero_shot_audio_classification.ZeroShotAudioClassificationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModel'>,), 'default': {'model': {'pt': ('laion/clap-htsat-fused', '973b6e5')}}, 'type': 'multimodal'}
image-classification
{'impl': <class 'transformers.pipelines.image_classification.ImageClassificationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForImageClassification'>,), 'default': {'model': {'pt': ('google/vit-base-patch16-224', '5dca96d'), 'tf': ('google/vit-base-patch16-224', '5dca96d')}}, 'type': 'image'}
image-feature-extraction
{'impl': <class 'transformers.pipelines.image_feature_extraction.ImageFeatureExtractionPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModel'>,), 'default': {'model': {'pt': ('google/vit-base-patch16-224', '3f49326'), 'tf': ('google/vit-base-patch16-224', '3f49326')}}, 'type': 'image'}
image-segmentation
{'impl': <class 'transformers.pipelines.image_segmentation.ImageSegmentationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForImageSegmentation'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSemanticSegmentation'>), 'default': {'model': {'pt': ('facebook/detr-resnet-50-panoptic', 'fc15262')}}, 'type': 'multimodal'}
image-to-text
{'impl': <class 'transformers.pipelines.image_to_text.ImageToTextPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForVision2Seq'>,), 'default': {'model': {'pt': ('ydshieh/vit-gpt2-coco-en', '65636df'), 'tf': ('ydshieh/vit-gpt2-coco-en', '65636df')}}, 'type': 'multimodal'}
object-detection
{'impl': <class 'transformers.pipelines.object_detection.ObjectDetectionPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForObjectDetection'>,), 'default': {'model': {'pt': ('facebook/detr-resnet-50', '2729413')}}, 'type': 'multimodal'}
zero-shot-object-detection
{'impl': <class 'transformers.pipelines.zero_shot_object_detection.ZeroShotObjectDetectionPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForZeroShotObjectDetection'>,), 'default': {'model': {'pt': ('google/owlvit-base-patch32', '17740e1')}}, 'type': 'multimodal'}
depth-estimation
{'impl': <class 'transformers.pipelines.depth_estimation.DepthEstimationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForDepthEstimation'>,), 'default': {'model': {'pt': ('Intel/dpt-large', 'e93beec')}}, 'type': 'image'}
video-classification
{'impl': <class 'transformers.pipelines.video_classification.VideoClassificationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForVideoClassification'>,), 'default': {'model': {'pt': ('MCG-NJU/videomae-base-finetuned-kinetics', '4800870')}}, 'type': 'video'}
mask-generation
{'impl': <class 'transformers.pipelines.mask_generation.MaskGenerationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForMaskGeneration'>,), 'default': {'model': {'pt': ('facebook/sam-vit-huge', '997b15')}}, 'type': 'multimodal'}
image-to-image
{'impl': <class 'transformers.pipelines.image_to_image.ImageToImagePipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForImageToImage'>,), 'default': {'model': {'pt': ('caidas/swin2SR-classical-sr-x2-64', '4aaedcb')}}, 'type': 'image'}

In [2]:
from transformers import pipeline, QuestionAnsweringPipeline

/home/wjc/miniconda3/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
pipe = pipeline('text-classification')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://hf-mirror.com/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--distilbert--distilbert-base-uncased-finetuned-sst-2-english/snapshots/714eb0fa89d2f80546fda750413ed43d93601a13/config.json
Model config DistilBertConfig {
  "_name_or_path": "distilbert/distilbert-base-uncased-finetuned-sst-2-english",
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "finetuning_task": "sst-2",
  "hidden_dim": 3072,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "initializer_range": 0.02,
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "output_past": true,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.44.1",
  "vocab_size": 30522
}

loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--distilbert--distilbert-base-uncased-finetuned-sst-2-english/snapshots/714eb0fa89d2f80546fda750413ed43d93601a13/config.json
Model config DistilBertConfig {
  "_name_or_path": "distilbert/distilbert-base-uncased-finetuned-sst-2-english",
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "finetuning_task": "sst-2",
  "hidden_dim": 3072,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "initializer_range": 0.02,
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "output_past": true,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.44.1",
  "vocab_size": 30522
}

loading weights file model.safetensors from cache at /home/wjc/.cache/huggingface/hub/models--distilbert--distilbert-base-uncased-finetuned-sst-2-english/snapshots/714eb0fa89d2f80546fda750413ed43d93601a13/model.safetensors
All model checkpoint weights were used when initializing DistilBertForSequenceClassification.

All the weights of DistilBertForSequenceClassification were initialized from the model checkpoint at distilbert/distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use DistilBertForSequenceClassification for predictions without further training.
loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--distilbert--distilbert-base-uncased-finetuned-sst-2-english/snapshots/714eb0fa89d2f80546fda750413ed43d93601a13/config.json
Model config DistilBertConfig {
  "_name_or_path": "distilbert/distilbert-base-uncased-finetuned-sst-2-english",
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "finetuning_task": "sst-2",
  "hidden_dim": 3072,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "initializer_range": 0.02,
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "output_past": true,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.44.1",
  "vocab_size": 30522
}

loading file vocab.txt from cache at /home/wjc/.cache/huggingface/hub/models--distilbert--distilbert-base-uncased-finetuned-sst-2-english/snapshots/714eb0fa89d2f80546fda750413ed43d93601a13/vocab.txt
loading file tokenizer.json from cache at None
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at None
loading file tokenizer_config.json from cache at /home/wjc/.cache/huggingface/hub/models--distilbert--distilbert-base-uncased-finetuned-sst-2-english/snapshots/714eb0fa89d2f80546fda750413ed43d93601a13/tokenizer_config.json
loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--distilbert--distilbert-base-uncased-finetuned-sst-2-english/snapshots/714eb0fa89d2f80546fda750413ed43d93601a13/config.json
Model config DistilBertConfig {
  "_name_or_path": "distilbert/distilbert-base-uncased-finetuned-sst-2-english",
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "finetuning_task": "sst-2",
  "hidden_dim": 3072,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "initializer_range": 0.02,
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "output_past": true,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.44.1",
  "vocab_size": 30522
}

/home/wjc/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--distilbert--distilbert-base-uncased-finetuned-sst-2-english/snapshots/714eb0fa89d2f80546fda750413ed43d93601a13/config.json
Model config DistilBertConfig {
  "_name_or_path": "distilbert/distilbert-base-uncased-finetuned-sst-2-english",
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "finetuning_task": "sst-2",
  "hidden_dim": 3072,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "initializer_range": 0.02,
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "output_past": true,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.44.1",
  "vocab_size": 30522
}

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [8]:
pipe('very good')

[{'label': 'POSITIVE', 'score': 0.9998520612716675}]

In [10]:
pipe = pipeline('text-classification', model = 'uer/roberta-base-finetuned-dianping-chinese')

loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--uer--roberta-base-finetuned-dianping-chinese/snapshots/25faf1874b21e76db31ea9c396ccf2a0322e0071/config.json
Model config BertConfig {
  "_name_or_path": "uer/roberta-base-finetuned-dianping-chinese",
  "architectures": [
    "BertForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "negative (stars 1, 2 and 3)",
    "1": "positive (stars 4 and 5)"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "negative (stars 1, 2 and 3)": 0,
    "positive (stars 4 and 5)": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.44.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 21128
}

loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--uer--roberta-base-finetuned-dianping-chinese/snapshots/25faf1874b21e76db31ea9c396ccf2a0322e0071/config.json
Model config BertConfig {
  "_name_or_path": "uer/roberta-base-finetuned-dianping-chinese",
  "architectures": [
    "BertForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "negative (stars 1, 2 and 3)",
    "1": "positive (stars 4 and 5)"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "negative (stars 1, 2 and 3)": 0,
    "positive (stars 4 and 5)": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.44.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 21128
}

loading weights file pytorch_model.bin from cache at /home/wjc/.cache/huggingface/hub/models--uer--roberta-base-finetuned-dianping-chinese/snapshots/25faf1874b21e76db31ea9c396ccf2a0322e0071/pytorch_model.bin
All model checkpoint weights were used when initializing BertForSequenceClassification.

All the weights of BertForSequenceClassification were initialized from the model checkpoint at uer/roberta-base-finetuned-dianping-chinese.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BertForSequenceClassification for predictions without further training.
loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--uer--roberta-base-finetuned-dianping-chinese/snapshots/25faf1874b21e76db31ea9c396ccf2a0322e0071/config.json
Model config BertConfig {
  "_name_or_path": "uer/roberta-base-finetuned-dianping-chinese",
  "architectures": [
    "BertForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "negative (stars 1, 2 and 3)",
    "1": "positive (stars 4 and 5)"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "negative (stars 1, 2 and 3)": 0,
    "positive (stars 4 and 5)": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.44.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 21128
}

loading file vocab.txt from cache at /home/wjc/.cache/huggingface/hub/models--uer--roberta-base-finetuned-dianping-chinese/snapshots/25faf1874b21e76db31ea9c396ccf2a0322e0071/vocab.txt
loading file tokenizer.json from cache at None
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at /home/wjc/.cache/huggingface/hub/models--uer--roberta-base-finetuned-dianping-chinese/snapshots/25faf1874b21e76db31ea9c396ccf2a0322e0071/special_tokens_map.json
loading file tokenizer_config.json from cache at /home/wjc/.cache/huggingface/hub/models--uer--roberta-base-finetuned-dianping-chinese/snapshots/25faf1874b21e76db31ea9c396ccf2a0322e0071/tokenizer_config.json
loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--uer--roberta-base-finetuned-dianping-chinese/snapshots/25faf1874b21e76db31ea9c396ccf2a0322e0071/config.json
Model config BertConfig {
  "_name_or_path": "uer/roberta-base-finetuned-dianping-chinese",
  "architectures": [
    "BertForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "negative (stars 1, 2 and 3)",
    "1": "positive (stars 4 and 5)"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "negative (stars 1, 2 and 3)": 0,
    "positive (stars 4 and 5)": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.44.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 21128
}

/home/wjc/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--uer--roberta-base-finetuned-dianping-chinese/snapshots/25faf1874b21e76db31ea9c396ccf2a0322e0071/config.json
Model config BertConfig {
  "_name_or_path": "uer/roberta-base-finetuned-dianping-chinese",
  "architectures": [
    "BertForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "negative (stars 1, 2 and 3)",
    "1": "positive (stars 4 and 5)"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "negative (stars 1, 2 and 3)": 0,
    "positive (stars 4 and 5)": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.44.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 21128
}

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [11]:
pipe('不行')

[{'label': 'negative (stars 1, 2 and 3)', 'score': 0.9920274615287781}]

In [12]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

# model  = AutoModelForSequenceClassification.from_pretrained('/data/wjc/models/Meta-Llama-3-8B-Instruct')
# tokenizer = AutoTokenizer.from_pretrained('/data/wjc/models/Meta-Llama-3-8B-Instruct')

# pipe = pipeline('text-classification', model = model, tokenizer = tokenizer)

In [16]:
pipe('不行')

[{'label': 'LABEL_0', 'score': 0.8429162502288818}]

In [4]:
qa_pipe = pipeline('question-answering', model = 'uer/roberta-base-chinese-extractive-qa', tokenizer = 'uer/roberta-base-chinese-extractive-qa')

/home/wjc/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [5]:
qa_pipe

In [6]:
QuestionAnsweringPipeline

transformers.pipelines.question_answering.QuestionAnsweringPipeline

In [7]:
qa_pipe('我是谁', '我是谁')

{'score': 2.0642194620279497e-09, 'start': 2, 'end': 3, 'answer': '谁'}

In [13]:
tokenizer = AutoTokenizer.from_pretrained("uer/roberta-base-chinese-extractive-qa")
model = AutoModelForSequenceClassification.from_pretrained("uer/roberta-base-chinese-extractive-qa")

/home/wjc/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at uer/roberta-base-chinese-extractive-qa and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [11]:
input_text = "我觉得不太行！"
inputs = tokenizer(input_text, return_tensors="pt")

In [12]:
inputs

{'input_ids': tensor([[ 101, 2769, 6230, 2533,  679, 1922, 6121, 8013,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [13]:
res = model(**inputs)
res

SequenceClassifierOutput(loss=None, logits=tensor([[0.0294, 0.0761]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [20]:
logits = res.logits
logits = torch.softmax(logits, dim=0)
logits
pred = torch.argmax(logits).item()
pred

0

In [15]:

import torch

In [21]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(21128, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

In [22]:
sen = "弱小的我也有大梦想!"

In [23]:
tokenizer

BertTokenizerFast(name_or_path='uer/roberta-base-chinese-extractive-qa', vocab_size=21128, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [24]:
tokens = tokenizer.tokenize(sen)
tokens

['弱', '小', '的', '我', '也', '有', '大', '梦', '想', '!']

In [25]:
tokenizer.tokenize

<bound method PreTrainedTokenizerFast.tokenize of BertTokenizerFast(name_or_path='uer/roberta-base-chinese-extractive-qa', vocab_size=21128, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}>

In [26]:
tokenizer.vocab

{'##隐': 20448,
 '##desk': 13039,
 '##ndi': 11874,
 '惟': 2668,
 '##tina': 10584,
 '##嫲': 15133,
 'な': 557,
 'hbl': 12502,
 '祇': 4856,
 '397': 12591,
 'jp': 9348,
 '503': 12929,
 'so': 8968,
 '##懵': 15810,
 '##邵': 19996,
 '颛': 7581,
 '##啄': 14611,
 '码': 4772,
 '娘': 2023,
 '邢': 6928,
 '##驍': 20764,
 '##蹺': 19762,
 '躬': 6717,
 'continue': 10859,
 'parker': 12495,
 '##ties': 11199,
 '##岘': 15324,
 'ては': 9418,
 '##潮': 17117,
 '睫': 4724,
 '墨': 1874,
 '##禁': 17938,
 '##记': 19438,
 '##鲸': 20898,
 '忪': 2570,
 '##仗': 13858,
 'ctrl': 8947,
 'bug': 8761,
 '##絲': 18244,
 '閉': 7273,
 '##lvin': 12745,
 'sign': 12710,
 '##＆': 21075,
 '篆': 5062,
 '##℃': 8320,
 '265': 8689,
 '##|': 13345,
 '濘': 4087,
 'x6': 12121,
 '##它': 15181,
 '##東': 16403,
 '焚': 4190,
 'ji': 12095,
 '##摒': 16091,
 '##︱': 21050,
 '◕': 475,
 'ᵒ': 335,
 'への': 11021,
 '##ɔ': 13367,
 'harry': 12296,
 '##ssion': 12726,
 '噸': 1697,
 '俐': 919,
 '##啲': 14633,
 '撵': 3068,
 '##療': 17672,
 '壮': 1896,
 'july': 8909,
 '奥': 1952,
 '沌': 3757,
 'jpg': 9248,
 '144': 9494,
 '##log': 11458,
 '##wing': 13070,
 '##媞': 15114,
 '鳍': 7846,
 '##岩': 15329,
 '儉': 1025,
 '##皰': 17707,
 '##稀': 17978,
 '##013': 11335,
 'emba': 10360,
 '##庭': 15488,
 '##ney': 10761,
 '##載': 19791,
 'ˢ': 209,
 'kbs': 10655,
 '責': 6519,
 '##ies': 8773,
 '##騰': 20759,
 '柵': 3396,
 'ｼ': 8090,
 'saas': 10362,
 '予': 750,
 '咆': 1467,
 '##柱': 16450,
 '腕': 5580,
 '##house': 9937,
 '處': 5993,
 '熨': 4227,
 '衄': 6118,
 '##蓋': 18958,
 'ｅ': 8055,
 '##褔': 19246,
 '激': 4080,
 'cbc': 8712,
 '2b': 10740,
 '郸': 6962,
 '##綦': 18258,
 '显': 3227,
 '##瑋': 17498,
 '##tte': 9786,
 '##立': 18046,
 '韓': 7502,
 '搀': 3006,
 'vsc': 10933,
 '##⋈': 13553,
 '杉': 3329,
 '##袋': 19207,
 'div': 11308,
 '割': 1200,
 '腰': 5587,
 'のこ': 13016,
 'bot': 11825,
 '##搶': 16081,
 'ㄞ': 659,
 '浦': 3855,
 '##塑': 14905,
 '##粤': 18170,
 '→': 370,
 '犹': 4310,
 '薬': 5960,
 '##潛': 17108,
 '##ame': 10816,
 '##党': 14111,
 '种': 4905,
 '315': 9613,
 '##tax': 13155,
 '欲': 3617,
 '##棱': 16539,
 '##轆': 19808,
 '\\': 139,
 '鏗': 7124,
 'p1': 11020,
 'article': 9122,
 '##树': 16466,
 '##紉': 18206,
 '##渥': 17001,
 '諭': 6323,
 '髂': 7762,
 '##﹂': 21054,
 '##亟': 13823,
 '蒜': 5886,
 '##_': 13343,
 '##濕': 17143,
 '##贵': 19643,
 '##ust': 12840,
 '殡': 3661,
 '##dra': 12753,
 '孟': 2106,
 '##祝': 17924,
 '視': 6213,
 '愍': 2691,
 '钜': 7161,
 '1868': 12590,
 '##頷': 20590,
 '张': 2476,
 '侨': 905,
 '##st': 8415,
 '呜': 1449,
 '1979': 8706,
 '##酚': 20042,
 '桂': 3424,
 '##誓': 19349,
 '痉': 4570,
 'e6': 11639,
 'framework': 12842,
 '013': 13034,
 '##擎': 16140,
 '##毘': 16743,
 '##節': 18116,
 '焰': 4195,
 '##劑': 14269,
 '弊': 2464,
 '##阐': 20388,
 '##慷': 15781,
 '○○': 9423,
 '175': 9251,
 '##姚': 15058,
 '零': 7439,
 '##times': 12288,
 '##慧': 15773,
 '叼': 1388,
 '##豪': 19555,
 'weeks': 11973,
 '恐': 2607,
 '##攤': 16170,
 'pepper': 11861,
 '##呂': 14493,
 '##琏': 17477,
 '##賦': 19605,
 '##跻': 19725,
 '##tings': 13288,
 '##留': 17579,
 '##返': 19876,
 '丫': 703,
 '欖': 3611,
 '上': 677,
 '##ger': 9289,
 '##健': 14035,
 '蛛': 6033,
 '##毕': 16741,
 '##捨': 16000,
 '##＠': 21088,
 'cloud': 10279,
 '逗': 6856,
 'talk2yam': 8767,
 '##west': 11887,
 '##冰': 14159,
 '##10': 8311,
 'ko': 10368,
 '##墓': 14924,
 '##婚': 15099,
 '##≒': 13543,
 '##帚': 15424,
 '##戈': 15819,
 '347': 12936,
 '懶': 2754,
 '##誠': 19353,
 '恶': 2626,
 '##熏': 17278,
 '汕': 3730,
 '殭': 3663,
 '續': 5265,
 '##歙': 16686,
 '潼': 4065,
 '氢': 3705,
 'iptv': 12844,
 '##妃': 15021,
 'muji': 13001,
 '谕': 6460,
 '##曳': 16347,
 '##阡': 20397,
 '##統': 18243,
 '##泵': 16865,
 '##蹑': 19749,
 '024': 13002,
 'はお': 13232,
 '训': 6378,
 '##汾': 16807,
 '##简': 18099,
 '崛': 2307,
 '##搓': 16070,
 '##甩': 17558,
 '##祖': 17919,
 '咤': 1483,
 '咣': 1482,
 '##宴': 15212,
 'spa': 8509,
 '诸': 6436,
 '椹': 3497,
 '##46': 9340,
 '毛': 3688,
 '##吧': 14473,
 '##rge': 10756,
 '##处': 14962,
 '##岀': 15315,
 '筷': 5039,
 '##终': 18360,
 '仇': 790,
 'gg': 10206,
 'eur': 11991,
 '##悸': 15711,
 '##狈': 17371,
 '##诏': 19462,
 '熠': 4226,
 '艰': 5680,
 '漏': 4026,
 '##祭': 17931,
 '##通': 19915,
 '029': 12801,
 '##葉': 18921,
 '##唯': 14603,
 '##pn': 12991,
 '##羹': 18473,
 '殒': 3656,
 '##孛': 15160,
 '##なる': 11666,
 'ｗ': 8073,
 '##ock': 9069,
 '邳': 6938,
 '##祁': 17911,
 '裴': 6179,
 '##纨': 18335,
 '匙': 1267,
 '战': 2773,
 '由': 4507,
 '##忽': 15632,
 '##赶': 19685,
 '漢': 4031,
 '譏': 6351,
 '膠': 5608,
 '驥': 7715,
 'job': 12539,
 '##芸': 18769,
 '詢': 6273,
 '##冒': 14145,
 '饅': 7635,
 'return': 12330,
 '##亦': 13828,
 '##匠': 14326,
 '##捣': 15998,
 '僱': 1017,
 '##臨': 18688,
 'bear': 13265,
 '##閱': 20345,
 '##颓': 20632,
 '##榫': 16587,
 '##蹿': 19764,
 'mmorpg': 13274,
 '##懊': 15804,
 '##娜': 15082,
 '##糠': 18194,
 '映': 3216,
 '滦': 4011,
 '##狼': 17388,
 'access': 11098,
 '##苇': 18776,
 '祯': 4875,
 '付': 802,
 '##三': 13733,
 '##js': 11124,
 '##剖': 14246,
 '##纺': 18350,
 '侧': 904,
 'chang': 11680,
 'kd': 12695,
 '〕': 527,
 '##嗪': 14693,
 '##豎': 19549,
 '急': 2593,
 '##且': 13741,
 '##変': 14964,
 '夫': 1923,
 '##娆': 15075,
 '##崖': 15361,
 '##29': 8887,
 '##ᅣ': 13471,
 '桉': 3429,
 '##竭': 18055,
 '##歳': 16699,
 '##挖': 15962,
 '禽': 4896,
 '##縷': 18300,
 '##✕': 13634,
 'or': 8549,
 '##れは': 9170,
 'gpa': 12273,
 'traction': 12600,
 '##狱': 17385,
 '詛': 6269,
 '苣': 5734,
 '賜': 6541,
 '轅': 6750,
 '迩': 6831,
 '2019': 9160,
 '骚': 7746,
 '砂': 4773,
 '顫': 7548,
 'tcp': 9901,
 'sports': 10646,
 '##sol': 12257,
 '##sia': 12557,
 '444': 12876,
 '##压': 14384,
 '##娠': 15084,
 '##条': 16397,
 '##臃': 18677,
 '##趸': 19699,
 '##69': 9398,
 '##驅': 20762,
 '藥': 5973,
 '墊': 1865,
 '76': 8399,
 '##鳩': 20910,
 '##糖': 18188,
 '##允': 14095,
 '1895': 10794,
 '##教': 16193,
 '##沈': 16812,
 'mtv': 11529,
 'language': 8348,
 'sina': 9606,
 '##餅': 20676,
 '##篆': 18119,
 '韵': 7510,
 '拦': 2882,
 '##м': 13411,
 '蘑': 5982,
 '瞳': 4749,
 '##ument': 11867,
 '##綽': 18269,
 '厘': 1330,
 '##僧': 14071,
 '黛': 7950,
 '｡': 8081,
 'web': 8353,
 '##71': 9097,
 '##鈣': 20105,
 '##ran': 10477,
 '##啓': 14616,
 '痔': 4574,
 '汆': 3725,
 '擋': 3081,
 '姥': 2005,
 '##ef': 9679,
 '##榜': 16585,
 '##蠱': 19170,
 '##跷': 19722,
 '##咛': 14538,
 '镁': 7250,
 '娼': 2035,
 '黃': 7941,
 '##犀': 17354,
 '##簿': 18146,
 'して': 8648,
 '[unused72]': 72,
 '##扁': 15850,
 '##澈': 17126,
 '##活': 16890,
 '##逼': 19930,
 '護': 6362,
 '门': 7305,
 '##酩': 20047,
 '鏞': 7126,
 '##ม': 13445,
 '鬥': 7784,
 'rss': 8605,
 '茲': 5760,
 '缈': 5350,
 '##テル': 12181,
 'td': 9287,
 '##氟': 16760,
 '##龚': 21045,
 '嘧': 1665,
 '##⒋': 13574,
 'ﾉ': 8093,
 '澤': 4075,
 '##烧': 17230,
 '##吮': 14479,
 '##剣': 14250,
 '蛋': 6028,
 '蕊': 5934,
 '618': 9048,
 '苓': 5725,
 '局': 2229,
 'v6': 11051,
 '[unused31]': 31,
 '##ますのて': 13071,
 '##詢': 19330,
 '飲': 7614,
 '閹': 7290,
 '##r3': 12549,
 '畹': 4536,
 '##媚': 15112,
 'cat': 10165,
 'secret': 11634,
 '彬': 2509,
 '1946': 9120,
 '熱': 4229,
 '##mporary': 12392,
 '##呻': 14517,
 '擾': 3101,
 '##fl': 11690,
 '##鱷': 20879,
 '[unused36]': 36,
 '##綵': 18265,
 'gmat': 13204,
 '鍋': 7102,
 '##隶': 20462,
 '稍': 4924,
 '##擊': 16137,
 '##參': 14404,
 'くの': 13167,
 '##fr': 13245,
 '##貸': 19583,
 '萁': 5841,
 '##涸': 16949,
 'lady': 8822,
 '5mm': 9394,
 '388': 11632,
 '##hoo': 12638,
 '1916': 10772,
 '漆': 4024,
 '∠': 383,
 '##last': 13177,
 '掷': 2980,
 '##俾': 13997,
 'ps': 8362,
 '##ㄎ': 13712,
 '##奪': 15011,
 '降': 7360,
 '##稿': 18000,
 '躉': 6710,
 '褶': 6195,
 '##驮': 20775,
 '討': 6245,
 '箕': 5049,
 '言': 6241,
 '##ら': 8732,
 'ト': 613,
 '星': 3215,
 '悪': 2646,
 '##腼': 18652,
 '##蝦': 19133,
 '楽': 3518,
 '##右': 14438,
 'php': 8531,
 '榷': 3535,
 'root': 8859,
 '訂': 6242,
 'jan': 9213,
 '爬': 4260,
 '308': 9793,
 '##瞌': 17791,
 '∶': 388,
 '痠': 4580,
 '##婁': 15094,
 '##膑': 18659,
 '##蹉': 19746,
 'discovery': 12748,
 '##sha': 12772,
 '纬': 5281,
 '甫': 4502,
 'china': 8873,
 '##咭': 14548,
 '饗': 7643,
 'した': 8819,
 'ㄏ': 655,
 '趸': 6642,
 '髒': 7766,
 '杨': 3342,
 '贤': 6570,
 '哺': 1529,
 '嘞': 1660,
 '##urt': 10857,
 '##ose': 10936,
 '##饥': 20702,
 '##馁': 20721,
 '##6': 8158,
 '邹': 6941,
 'bloomberg': 10313,
 '晷': 3254,
 '蛊': 6027,
 'press': 9228,
 '２４': 12620,
 '##將': 15257,
 '##俺': 13996,
 '##鍵': 20164,
 '勇': 1235,
 '[unused73]': 73,
 'ا': 261,
 '缕': 5355,
 '踏': 6672,
 '##甲': 17565,
 'how': 9510,
 '男': 4511,
 '##ging': 12374,
 '##學': 15176,
 '##擲': 16153,
 '##娲': 15089,
 '##享': 13832,
 '##堡': 14893,
 '##鎧': 20175,
 'loftpermalink': 10056,
 '##琴': 17490,
 '##鑲': 20203,
 '冰': 1102,
 '##阕': 20391,
 '戟': 2776,
 'morning': 12885,
 '##ウ': 12891,
 '##º': 13358,
 '咔': 1474,
 '##001': 9942,
 '##珍': 17454,
 '##勖': 14298,
 '##甜': 17551,
 '227': 10543,
 '##簽': 18144,
 '##遴': 19961,
 'r2': 11345,
 '役': 2514,
 '骏': 7742,
 '248': 11009,
 '产': 772,
 '煜': 4207,
 '狹': 4330,
 '##峭': 15347,
 'start': 10906,
 '孿': 2122,
 '♦': 492,
 '朋': 3301,
 '##托': 15862,
 '萩': 5856,
 '##公': 14119,
 '罚': 5385,
 '勛': 1244,
 '罵': 5393,
 '500ml': 13023,
 '##ㄌ': 13710,
 '##臼': 18696,
 '##镌': 20311,
 '##掲': 16034,
 'ice': 10490,
 '[unused69]': 69,
 '肄': 5485,
 '待': 2521,
 '簫': 5084,
 '207': 10194,
 'alexander': 11733,
 '##泷': 16866,
 '督': 4719,
 'pcb': 9925,
 'ㄇ': 649,
 '躁': 6708,
 '淚': 3907,
 '316': 10743,
 '灿': 4136,
 '##ian': 8750,
 '##ction': 9116,
 '杂': 3325,
 'mate': 10577,
 '##啱': 14632,
 '##珪': 17464,
 '窯': 4982,
 '##茅': 18804,
 '##辊': 19836,
 '##般': 18720,
 '##鉤': 20119,
 '##頼': 20594,
 '诛': 6412,
 '棱': 3482,
 'ex': 9577,
 'sport': 10669,
 '##楠': 16564,
 '##蛾': 19099,
 'way': 10590,
 '纵': 5288,
 '##贮': 19637,
 '胥': 5531,
 '##杠': 16396,
 '嫁': 2063,
 '卿': 1321,
 '##aka': 12417,
 '1953': 9268,
 '##湊': 17014,
 '掺': 2982,
 '署': 5392,
 '业': 689,
 'logo': 8529,
 '滁': 3991,
 '隋': 7387,
 '1911': 10041,
 '彈': 2492,
 '##俄': 13972,
 '##纹': 18349,
 'raw': 11265,
 '##臺': 18694,
 '##骄': 20791,
 '蹉': 6689,
 '徼': 2550,
 '匿': 1280,
 '桀': 3422,
 '舌': 5649,
 '佐': 858,
 '轮': 6762,
 'puma': 11803,
 '##呕': 14502,
 '##瑪': 17511,
 '[unused89]': 89,
 '咗': 1477,
 '慨': 2717,
 '網': 5206,
 '##嘈': 14705,
 '坛': 1781,
 '##柠': 16444,
 '##谨': 19531,
 '##cker': 10603,
 'place': 10963,
 '申': 4509,
 '聆': 5463,
 '凜': 1124,
 '##fi': 9864,
 'sb': 12359,
 '唏': 1537,
 'network': 10339,
 '宣': 2146,
 '##dk': 12806,
 '##櫻': 16664,
 '##荡': 18839,
 'id': 8231,
 '##虬': 19059,
 '舞': 5659,
 '##男': 17568,
 '##黍': 21000,
 '##お': 8345,
 '##琺': 17493,
 'english': 8899,
 '[unused46]': 46,
 '乎': 725,
 '##jy': 13051,
 '##雋': 20475,
 '惇': 2660,
 '##闰': 20368,
 'eco': 12791,
 '##］': 21091,
 '游': 3952,
 '##蜓': 19109,
 '拋': 2862,
 '拓': 2868,
 '炕': 4145,
 '##術': 19180,
 '緒': 5219,
 '蜗': 6054,
 '##苹': 18798,
 '##页': 20609,
 '##鬼': 20844,
 '##ku': 9547,
 '##blog': 10877,
 '3mm': 12064,
 '詩': 6276,
 '襟': 6199,
 '揩': 2997,
 '##墜': 14928,
 '仓': 797,
 '##る': 8481,
 '##氖': 16756,
 '拾': 2896,
 '##mma': 13292,
 '5g': 8711,
 'hola': 10961,
 '党': 1054,
 '▲topoct': 10135,
 'udnbkk': 11339,
 '##94': 9723,
 '蹶': 6704,
 '512': 11530,
 '曰': 3288,
 '常': 2382,
 '铐': 7196,
 '##胫': 18590,
 '响': 1510,
 '嶺': 2327,
 '頤': 7529,
 '666': 11186,
 '也': 738,
 '群': 5408,
 '##隈': 20442,
 '##湃': 17012,
 '蒹': 5893,
 '伶': 846,
 'ᄏ': 300,
 '粄': 5105,
 '卅': 1284,
 '裤': 6175,
 '屿': 2257,
 'mpv': 10259,
 '##下': 13735,
 '##仨': 13867,
 '##崩': 15366,
 '濺': 4098,
 '頒': 7523,
 '瓶': 4486,
 'protected': 9562,
 '##㗎': 13727,
 '##至': 18692,
 '凌': 1119,
 '堿': 1845,
 '##郅': 20002,
 '手': 2797,
 '眨': 4699,
 '##ire': 9764,
 '躏': 6714,
 '##猛': 17395,
 '泊': 3788,
 '##调': 19501,
 '##蹤': 19754,
 '##阮': 20399,
 '##愿': 15760,
 '##みませんか': 11775,
 '{': 169,
 '滲': 4016,
 '篓': 5066,
 '##②': 13557,
 '་': 286,
 '##歲': 16698,
 '373': 12779,
 '##洱': 16884,
 '##猕': 17391,
 '[unused66]': 66,
 '##笔': 18068,
 '觥': 6238,
 '##ェ': 12690,
 'ø': 194,
 '##睛': 17771,
 'paul': 8999,
 '篠': 5069,
 '湿': 3969,
 '鷗': 7875,
 '##亞': 13822,
 'p3': 12454,
 '##壩': 14950,
 '##壬': 14952,
 '８': 8036,
 '曖': 3281,
 '##盼': 17744,
 'はしめまして': 13012,
 '##sl': 11066,
 '##ve': 8519,
 '▫': 462,
 '##情': 15715,
 '1850': 12631,
 '1902': 11487,
 '##ォ': 13683,
 '##院': 20425,
 '##ir': 8977,
 'first': 9555,
 '##﹔': 21060,
 '矍': 4754,
 '##軟': 19784,
 '##辽': 19865,
 '##鳳': 20911,
 '遴': 6904,
 '騰': 7702,
 '335': 11728,
 '潛': 4051,
 'は': 562,
 '##別': 14219,
 'された': 10438,
 '##锣': 20293,
 '偉': 971,
 '##mbps': 12399,
 '##繹': 18318,
 '##滇': 17052,
 '歲': 3641,
 '］': 8047,
 'junior': 12552,
 'あり': 10617,
 '隻': 7407,
 '悲': 2650,
 '##閉': 20330,
 '綺': 5210,
 '盐': 4663,
 '##獾': 17427,
 'cell': 11490,
 '##las': 10113,
 '勖': 1241,
 'ه': 272,
 '惴': 2683,
 '辻': 6806,
 '##facebook': 12917,
 '澳': 4078,
 '##木': 16369,
 'pptv': 12123,
 '##筏': 18084,
 '##絨': 18241,
 'orz': 10836,
 '##茼': 18823,
 '##漪': 17091,
 '钱': 7178,
 '##衿': 19201,
 '##貞': 19567,
 '氰': 3715,
 '##屑': 15301,
 '##恒': 15665,
 '##谜': 19523,
 '焗': 4187,
 '511': 12677,
 '##邹': 19998,
 '##鸥': 20943,
 'not': 9059,
 '揍': 2988,
 '袞': 6155,
 'のないフロクに': 10900,
 '##蚓': 19070,
 '##奏': 14998,
 '##燜': 17301,
 '喏': 1594,
 'chinese': 10101,
 '##のは': 10093,
 '##憨': 15793,
 '##醮': 20074,
 '##饰': 20709,
 '##００': 9885,
 '##urg': 13143,
 '##旌': 16239,
 '##染': 16438,
 '##幡': 15450,
 'してみてくたさいね': 12142,
 '餡': 7630,
 '##锦': 20296,
 '##app': 11259,
 '##致': 18693,
 '14k': 10612,
 'shtml': 11501,
 '##兮': 14121,
 '##琰': 17487,
 'alphago': 10941,
 '艋': 5674,
 '鱿': 7825,
 '牺': 4295,
 'a5': 10796,
 'mp4': 9399,
 '##urn': 12760,
 '##觞': 19293,
 '啡': 1565,
 '##cs': 9761,
 '褪': 6192,
 '[unused2]': 2,
 '##ter': 8457,
 '##湫': 17021,
 '##vo': 10701,
 '##鈍': 20100,
 '##髮': 20830,
 'field': 12594,
 '256': 9745,
 '鞘': 7494,
 '户': 2787,
 '##嫑': 15124,
 '是': 3221,
 '##摩': 16097,
 '##en': 8329,
 '鍰': 7106,
 '孵': 2118,
 '##;': 13333,
 '##嫘': 15127,
 '##统': 18377,
 '耀': 5438,
 '##挝': 15966,
 '亮': 778,
 'sbs': 9965,
 '##虹': 19061,
 'sale': 12133,
 '##鹂': 20954,
 'mode': 10770,
 '##迸': 19895,
 '砝': 4781,
 '##促': 13971,
 '★★★★★': 10349,
 '##坍': 14831,
 '##易': 16268,
 '##light': 9638,
 '##丼': 13770,
 '盒': 4665,
 '甦': 4499,
 '##晷': 16311,
 '太': 1922,
 '贍': 6559,
 '啬': 1572,
 '惭': 2677,
 '##sd': 10117,
 '##ティー': 12841,
 '##鑄': 20196,
 'ｌ': 8062,
 '榆': 3521,
 '##盒': 17722,
 '慣': 2715,
 '浑': 3847,
 '歛': 3630,
 '##独': 17381,
 '掰': 2976,
 '獨': 4360,
 'wam': 9667,
 'e5': 10695,
 '戈': 2762,
 'mems': 12530,
 'autocad': 12796,
 '捶': 2948,
 'smap': 13175,
 '##喷': 14670,
 '##囟': 14784,
 '##铃': 20247,
 '##镯': 20322,
 '﹙': 8007,
 '##╚': 13588,
 '##喃': 14643,
 '##@': 13338,
 '##淘': 16962,
 '##絕': 18236,
 'market': 9095,
 'mvp': 9505,
 '##pc': 10022,
 '##ye': 10522,
 '骋': 7740,
 'dha': 11015,
 '膺': 5613,
 '鶴': 7874,
 'des': 11081,
 '##羁': 18453,
 ...}

In [27]:
tokenizer.vocab_size

21128

In [28]:
# 将词序列转换为id序列
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[2483, 2207, 4638, 2769, 738, 3300, 1920, 3457, 2682, 106]

In [29]:
tokens = tokenizer.convert_ids_to_tokens(ids)

In [30]:
tokens

['弱', '小', '的', '我', '也', '有', '大', '梦', '想', '!']

In [31]:
tokenizer.tokenize('我')

['我']

In [32]:
ids = tokenizer.encode(sen)

In [33]:
ids

[101, 2483, 2207, 4638, 2769, 738, 3300, 1920, 3457, 2682, 106, 102]

In [34]:
str_sen = tokenizer.decode(ids)
str_sen

'[CLS] 弱 小 的 我 也 有 大 梦 想! [SEP]'

In [36]:
ids = tokenizer.encode(sen, padding="max_length", max_length=20)
ids

[101,
 2483,
 2207,
 4638,
 2769,
 738,
 3300,
 1920,
 3457,
 2682,
 106,
 102,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [37]:
atten_mask = [1 if i != 0 else 0 for i in ids]
atten_mask

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]

In [38]:
inputs = tokenizer.encode_plus(sen, return_tensors="pt", padding="max_length", max_length=20)
inputs

{'input_ids': tensor([[ 101, 2483, 2207, 4638, 2769,  738, 3300, 1920, 3457, 2682,  106,  102,
            0,    0,    0,    0,    0,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

In [39]:
inputs = tokenizer(sen, return_tensors="pt", padding="max_length", max_length=20)

In [40]:
inputs

{'input_ids': tensor([[ 101, 2483, 2207, 4638, 2769,  738, 3300, 1920, 3457, 2682,  106,  102,
            0,    0,    0,    0,    0,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

In [41]:
sens = ["弱小的我也有大梦想",
        "有梦想谁都了不起",
        "追逐梦想的心，比梦想本身，更可贵"]
res = tokenizer(sens)
res

{'input_ids': [[101, 2483, 2207, 4638, 2769, 738, 3300, 1920, 3457, 2682, 102], [101, 3300, 3457, 2682, 6443, 6963, 749, 679, 6629, 102], [101, 6841, 6852, 3457, 2682, 4638, 2552, 8024, 3683, 3457, 2682, 3315, 6716, 8024, 3291, 1377, 6586, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [42]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [45]:
import pandas as pd

data = pd.read_csv('/home/wjc/mllm/mllm_from_scratch/learn_transformers/transformers-code/01-Getting Started/04-model/ChnSentiCorp_htl_all.csv')
data

      label                                             review
0         1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1         1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2         1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3         1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4         1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风
...     ...                                                ...
7761      0  尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762      0  盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763      0  看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764      0  我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
7765      0  说实在的我很失望，之前看了其他人的点评后觉得还可以才去的，结果让我们大跌眼镜。我想这家酒店以...

[7766 rows x 2 columns]

In [46]:
data = data.dropna()
data

      label                                             review
0         1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1         1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2         1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3         1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4         1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风
...     ...                                                ...
7761      0  尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762      0  盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763      0  看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764      0  我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
7765      0  说实在的我很失望，之前看了其他人的点评后觉得还可以才去的，结果让我们大跌眼镜。我想这家酒店以...

[7765 rows x 2 columns]

In [48]:
from torch.utils.data import Dataset, DataLoader

In [49]:
class MyDataset(Dataset):
    def __init__(self) -> None:
        super().__init__()
        self.data = pd.read_csv('/home/wjc/mllm/mllm_from_scratch/learn_transformers/transformers-code/01-Getting Started/04-model/ChnSentiCorp_htl_all.csv')
        self.data = self.data.dropna()
    def __getitem__(self, index):
        return self.data.iloc[index]['review'], self.data.iloc[index]['label']
    
    def __len__(self):
        return len(self.data)

In [50]:
import pandas as pd
dataset  = MyDataset()
for i in range(5):
    print(dataset[i])

('距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较为简单.', 1)
('商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!', 1)
('早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。', 1)
('宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小，但加上低价位因素，还是无超所值的；环境不错，就在小胡同内，安静整洁，暖气好足-_-||。。。呵还有一大优势就是从宾馆出发，步行不到十分钟就可以到梅兰芳故居等等，京味小胡同，北海距离好近呢。总之，不错。推荐给节约消费的自助游朋友~比较划算，附近特色小吃很多~', 1)
('CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风', 1)

In [51]:
def collate_func(batch):
    texts, labels = [], []
    for item in batch:
        texts.append(item[0])
        labels.append(item[1])
    inputs = tokenizer(texts, return_tensors="pt", padding="max_length", max_length=128,                # 启用自动填充
        truncation=True, )
    inputs['labels'] = torch.tensor(labels)
    return inputs

In [52]:
from torch.utils.data import DataLoader

train_loader = DataLoader(dataset, batch_size=2, shuffle=True, collate_fn=collate_func)
vaild_loader = DataLoader(dataset, batch_size=2, shuffle=False, collate_fn=collate_func)

In [53]:
train_loader

In [54]:
vaild_loader

In [15]:
import torch

In [57]:
next(enumerate(vaild_loader))[1]

{'input_ids': tensor([[ 101, 6655, 4895, 2335, 3763, 1062, 6662, 6772, 6818,  117,  852, 3221,
         1062,  769, 2900, 4850,  679, 2190,  117, 1963, 3362, 3221,  107, 5918,
         7355, 5296,  107, 4638, 6413,  117,  833, 7478, 2382, 7937, 4172,  119,
         2456, 6379, 4500, 1166, 4638, 6662, 5296,  119, 2791, 7313, 6772,  711,
         5042, 1296,  119,  102,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0],
        [ 101, 1555, 1218, 1920, 2414, 2791, 8024, 2791, 7313, 2523, 1920, 8024,
         2414, 3300,  100, 2160, 8024, 3146,  860, 2697, 6230, 5307, 3845, 2141,
         2669,  679, 7231,  106,  102,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]), 'labels': tensor([1, 1])}

In [17]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(21128, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

In [18]:
from torch.optim import Adam
optimizer = Adam(model.parameters(), lr=2e-5)

In [43]:
from torch.optim import Adam


if torch.cuda.is_available():
    model = model.cuda()

In [44]:
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 2e-05
    maximize: False
    weight_decay: 0
)

In [45]:
with torch.inference_mode():

    for batch in vaild_loader:
        if torch.cuda.is_available():
            batch = {k: v.cuda() for k, v in batch.items}
        print(batch)

TypeError: 'method' object is not iterable

In [46]:
def evaluate():
    model.eval()
    acc_num = 0
    with torch.inference_mode():
        for batch in vaild_loader:
            if torch.cuda.is_available():
                batch = {k: v.cuda() for k, v in batch.items()}
                print(batch.items)
            output = model(**batch)
            pred = torch.argmax(output.logits, dim = -1)
            acc_num += (pred.long() == batch['labels'].long()).float().sum()
    return  acc_num/len(vaild_loader)
def train(epoch=3 , log_step=100):
    global_step =0
    for ep in range(epoch):
        model.train()
        for batch in train_loader:
            if torch.cuda.is_available():
                batch = {k: v.cuda() for k, v in batch.items}
            optimizer.zero_grad()
            output = model(**batch)
            output.loss.backward()
            optimizer.step()
            if global_step % log_step == 0:
                print(f"ep: {ep}, global_step: {global_step}, loss: {output.loss.item()}")
            global_step += 1
        acc = evaluate()
        print(f"ep: {ep}, acc: {acc}")

In [56]:
train()

TypeError: 'method' object is not iterable

In [3]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from datasets import load_dataset

In [2]:
!pip install datasets

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting datasets
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d7/84/0df6c5981f5fc722381662ff8cfbdf8aad64bec875f75d80b55bfef394ce/datasets-3.2.0-py3-none-any.whl (480 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 1.4 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: filelock in /home/wjc/miniconda3/lib/python3.12/site-packages (from datasets) (3.15.4)
Requirement already satisfied: numpy>=1.17 in /home/wjc/miniconda3/lib/python3.12/site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /home/wjc/miniconda3/lib/python3.12/site-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /home/wjc/miniconda3/lib/python3.12/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /home/wjc/miniconda3/lib/python3.12/site-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /home/wjc/miniconda3/lib/python3.12/site-packages (from datasets) (2.32.2)
Requirement already satisfied: tqdm>=4.66.3 in /home/wjc/miniconda3/lib/python3.12/site-packages (from datasets) (4.66.4)
Collecting xxhash (from datasets)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/11/a7/81dba5010f7e733de88af9555725146fc133be97ce36533867f4c7e75066/xxhash-3.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.4/194.4 kB 15.3 MB/s eta 0:00:00
Requirement already satisfied: multiprocess<0.70.17 in /home/wjc/miniconda3/lib/python3.12/site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /home/wjc/miniconda3/lib/python3.12/site-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.6.1)
Collecting aiohttp (from datasets)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/40/7f/6de218084f9b653026bd7063cd8045123a7ba90c25176465f266976d8c82/aiohttp-3.11.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 14.0 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: huggingface-hub>=0.23.0 in /home/wjc/miniconda3/lib/python3.12/site-packages (from datasets) (0.24.6)
Requirement already satisfied: packaging in /home/wjc/miniconda3/lib/python3.12/site-packages (from datasets) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /home/wjc/miniconda3/lib/python3.12/site-packages (from datasets) (6.0.1)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->datasets)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b9/74/fbb6559de3607b3300b9be3cc64e97548d55678e44623db17820dbd20002/aiohappyeyeballs-2.4.4-py3-none-any.whl (14 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->datasets)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ec/6a/bc7e17a3e87a2985d3e8f4da4cd0f481060eb78fb08596c42be62c90a4d9/aiosignal-1.3.2-py2.py3-none-any.whl (7.6 kB)
Collecting attrs>=17.3.0 (from aiohttp->datasets)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/89/aa/ab0f7891a01eeb2d2e338ae8fecbe57fcebea1a24dbb64d45801bfab481d/attrs-24.3.0-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.4/63.4 kB 2.4 MB/s eta 0:00:00
Collecting frozenlist>=1.1.1 (from aiohttp->datasets)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/af/f2/64b73a9bb86f5a89fb55450e97cd5c1f84a862d4ff90d9fd1a73ab0f64a5/frozenlist-1.5.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (283 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.6/283.6 kB 5.0 MB/s eta 0:00:0000:01
Collecting multidict<7.0,>=4.5 (from aiohttp->datasets)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d3/c8/529101d7176fe7dfe1d99604e48d69c5dfdcadb4f06561f465c8ef12b4df/multidict-6.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.0/131.0 kB 2.7 MB/s eta 0:00:00a 0:00:01
Collecting propcache>=0.2.0 (from aiohttp->datasets)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1c/07/ebe102777a830bca91bbb93e3479cd34c2ca5d0361b83be9dbd93104865e/propcache-0.2.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (243 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.6/243.6 kB 20.7 MB/s eta 0:00:00
Collecting yarl<2.0,>=1.17.0 (from aiohttp->datasets)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1a/e1/a097d5755d3ea8479a42856f51d97eeff7a3a7160593332d98f2709b3580/yarl-1.18.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (336 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 336.9/336.9 kB 14.5 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/wjc/miniconda3/lib/python3.12/site-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/wjc/miniconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/wjc/miniconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/wjc/miniconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/wjc/miniconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (2024.7.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/wjc/miniconda3/lib/python3.12/site-packages (from pandas->datasets) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /home/wjc/miniconda3/lib/python3.12/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/wjc/miniconda3/lib/python3.12/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /home/wjc/miniconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Installing collected packages: xxhash, propcache, multidict, frozenlist, attrs, aiohappyeyeballs, yarl, aiosignal, aiohttp, datasets
Successfully installed aiohappyeyeballs-2.4.4 aiohttp-3.11.11 aiosignal-1.3.2 attrs-24.3.0 datasets-3.2.0 frozenlist-1.5.0 multidict-6.1.0 propcache-0.2.1 xxhash-3.5.0 yarl-1.18.3

In [1]:
### 简化版本

In [3]:
import torch
import torch.nn as nn
import math

class selfattention(nn.Module):
    def __init__(self, hidden_dim: int = 512) -> None:
        super().__init__()

        self.hidden_dim = hidden_dim
        self.q_proj = nn.Linear(hidden_dim, hidden_dim)
        self.k_proj = nn.Linear(hidden_dim, hidden_dim)
        self.v_proj = nn.Linear(hidden_dim, hidden_dim)


    def forward(self, x):

        q = self.q_proj(x)
        k = self.k_proj(x)
        v = self.v_proj(x)

        atten_value = torch.matmul(q, k.transpose(-1, -2)
                                   )
        atten_weight = torch.softmax(atten_value / math.sqrt(self.hidden_dim),dim=-1)
        output = torch.matmul(atten_weight, v)
        return output

x= torch.rand(2,3,4)
self_atten = selfattention(4)
res = self_atten(x)

In [4]:
res

tensor([[[-0.3434, -0.1586, -0.0692,  0.5237],
         [-0.3405, -0.1619, -0.0668,  0.5269],
         [-0.3432, -0.1589, -0.0692,  0.5237]],

        [[-0.3293, -0.3130, -0.1228,  0.4577],
         [-0.3289, -0.3130, -0.1239,  0.4602],
         [-0.3289, -0.3130, -0.1239,  0.4604]]], grad_fn=<UnsafeViewBackward0>)

In [8]:
class self_attenv2(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dim = dim
        self.qkv_proj = nn.Linear(dim, dim*3)

    def forward(self,x):
        qkv = self.qkv_proj(x)
        q,k,v = torch.split(qkv, self.dim, dim=-1)
        atten_value = q @ k.transpose(-1, -2)
        atten_weight = torch.softmax(atten_value / math.sqrt(self.dim), dim=-1) @ v
        return atten_weight
    
x= torch.rand(2,3,4)
self_atten = self_attenv2(4)
res = self_atten(x)
res

tensor([[[ 0.4147, -0.2185, -0.0133,  0.6002],
         [ 0.4145, -0.2180, -0.0134,  0.5999],
         [ 0.4155, -0.2197, -0.0121,  0.6017]],

        [[ 0.3231,  0.0105, -0.1812,  0.6127],
         [ 0.3246,  0.0080, -0.1790,  0.6140],
         [ 0.3288,  0.0018, -0.1744,  0.6169]]], grad_fn=<UnsafeViewBackward0>)

In [13]:
class self_attenv3(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dim = dim
        self.qkv_proj = nn.Linear(dim, dim*3)
        self.att_drop = nn.Dropout(0.1)
        self.out_proj = nn.Linear(dim, dim)
        

    def forward(self,x, mask=None):
        qkv = self.qkv_proj(x)
        q,k,v = torch.split(qkv, self.dim, dim=-1)
        atten_value = q @ k.transpose(-1,-2)/math.sqrt(self.dim)
        if mask is not None:
            atten_value = atten_value.masked_fill(mask == 0, float('1e-20'))
        atten_weight = torch.softmax(atten_value, dim=-1)
        atten_weight = self.att_drop(atten_weight)
        atten_weight = atten_weight @ v
        atten_weight = self.out_proj(atten_weight)

        return atten_weight
    
x= torch.rand(2,3,4)
mask = torch.tensor([[1,1,0],[1,0,0]])
print(mask.shape)
print(mask)
mask = mask.unsqueeze(1)
print(mask.shape)
print(mask)
mask = mask.repeat(1,3,1)
print(mask.shape)
mask

self_atten = self_attenv3(4)
res = self_atten(x, mask)
res

torch.Size([2, 3])
tensor([[1, 1, 0],
        [1, 0, 0]])
torch.Size([2, 1, 3])
tensor([[[1, 1, 0]],

        [[1, 0, 0]]])
torch.Size([2, 3, 3])

tensor([[[-0.0266, -0.3372, -0.0219,  0.3664],
         [-0.0289, -0.3353, -0.0213,  0.3676],
         [-0.1421, -0.2271, -0.0186,  0.4151]],

        [[-0.0778, -0.2818,  0.0121,  0.3841],
         [-0.1552, -0.2064,  0.0116,  0.4001],
         [-0.0773, -0.2828,  0.0119,  0.3836]]], grad_fn=<ViewBackward0>)

In [14]:
import torch

In [37]:
class MultiHeadAttention(nn.Module):
    def __init__(self, dim, head_nums):
        super().__init__()
        self.dim = dim
        self.head_nums = head_nums
        self.head_dim = dim // head_nums

        self.q_proj = nn.Linear(dim, dim)
        self.k_proj = nn.Linear(dim, dim)
        self.v_proj = nn.Linear(dim, dim)
        self.out_proj = nn.Linear(dim, dim)

        self.att_drop = nn.Dropout(0.1)

    def forward(self, x, mask=None):
        batch, sqlen, _ = x.size()
        q = self.q_proj(x)
        k = self.k_proj(x)
        v = self.v_proj(x)

        q = q.view(batch, sqlen, self.head_nums, self.head_dim).transpose(1, 2)
        k = k.view(batch, sqlen, self.head_nums, self.head_dim).transpose(1, 2)
        v = v.view(batch, sqlen, self.head_nums, self.head_dim).transpose(1, 2)

        atten_value = q @ k.transpose(-2, -1) / math.sqrt(self.head_dim)
        if mask is not None:
            atten_value = atten_value.masked_fill(mask == 0, float('1e-20'))
        atten_weight = torch.softmax(atten_value, dim=-1)
        atten_weight = self.att_drop(atten_weight)

        atten_weight = atten_weight @ v
        atten_weight = atten_weight.transpose(1, 2).contiguous().view(batch, sqlen, self.dim)
        atten_weight = self.out_proj(atten_weight)
        return atten_weight
    
x= torch.rand(2,3,4)
mask = torch.tensor([[1,1,0],[1,0,0]])
print(mask.shape)
print(mask)

mask = mask.unsqueeze(1)
print(mask.shape)

mask = mask.repeat(1,3,1)
print(mask.shape)
mask

multi_head_atten = MultiHeadAttention(4, 2)
res = multi_head_atten(x, mask)
res

torch.Size([2, 3])
tensor([[1, 1, 0],
        [1, 0, 0]])
torch.Size([2, 1, 3])
torch.Size([2, 3, 3])

tensor([[[-0.3476, -0.6457, -0.3724, -0.2713],
         [-0.3718, -0.5966, -0.3963, -0.2944],
         [-0.3500, -0.6461, -0.3714, -0.2697]],

        [[-0.4167, -0.5465, -0.4235, -0.2751],
         [-0.4932, -0.6148, -0.3497, -0.1838],
         [-0.4934, -0.6163, -0.3503, -0.1841]]], grad_fn=<ViewBackward0>)

In [39]:
class simpleDecoder(nn.Module):
    def __init__(self, dim, head_nums):
        super().__init__()
        self.dim = dim
        self.head_nums = head_nums
        self.head_dim = dim // head_nums

        self.atten_layerNorm = nn.LayerNorm(dim, eps=1e-5)

        self.q_proj = nn.Linear(dim, dim)
        self.k_proj = nn.Linear(dim, dim)
        self.v_proj = nn.Linear(dim, dim)
        self.out_proj = nn.Linear(dim, dim)

        self.att_drop = nn.Dropout(0.1)
        # self.fnn_layernorm1 = nn.LayerNorm(dim, esp = 1e-5)

        self.up = nn.Linear(dim, dim * 4)
        self.down = nn.Linear(dim * 4, dim)
        self.fnn_layernorm2 = nn.LayerNorm(dim, eps = 1e-5)
        self.act_fn = nn.GELU()
        self.fnn_drop = nn.Dropout(0.1)

    def atten_output(self, q, k, v, mask=None):
        atten_value = q @ k.transpose(-2, -1) / math.sqrt(self.head_dim)

        if mask is not None:
            mask = mask.tril()
            atten_value = atten_value.masked_fill(mask == 0, float('-inf'))
        else:
            mask = torch.ones_like(atten_value).tril()
            atten_value = atten_value.masked_fill(mask == 0, float('-inf'))

        
        print(mask.shape)
        print(mask)

        atten_weight = torch.softmax(atten_value, dim=-1)
        atten_weight = self.att_drop(atten_weight)
        atten_weight = atten_weight @ v
        batch, head_nums, sqlen, head_dim = atten_weight.size()
        atten_weight = atten_weight.transpose(1, 2).contiguous().view(batch, sqlen, self.dim)
        atten_weight = self.out_proj(atten_weight)
        return atten_weight


    def block_block(self, x, mask=None):
        batch, sqlen, _ = x.size()
        q = self.q_proj(x)
        k = self.k_proj(x)
        v = self.v_proj(x)

        q = q.view(batch, sqlen, self.head_nums, self.head_dim).contiguous().transpose(1, 2)
        k = k.view(batch, sqlen, self.head_nums, self.head_dim).contiguous().transpose(1, 2)
        v = v.view(batch, sqlen, self.head_nums, self.head_dim).contiguous().transpose(1, 2)

        atten = self.atten_output(q, k, v, mask)
        atten = atten + x
        atten = self.atten_layerNorm(atten)
        return atten
    def fnn_block(self, x):
        up = self.up(x)
        up = self.act_fn(up)
        down = self.down(up)
        return self.fnn_layernorm2(down + x)
    
    def forward(self, x, mask=None):
        x = self.block_block(x, mask)
        x = self.fnn_block(x)
        return x
    
class decoder(nn.Module):
    def __init__(self, dim, head_nums, layers):
        super().__init__()
        self.layer_list = nn.ModuleList([simpleDecoder(dim, head_nums) for _ in range(layers)])
        self.emb = nn.Embedding(100, dim)
        self.out = nn.Linear(dim, 100)

    def forward(self, x, mask=None):
        x = self.emb(x)
        for i,l in enumerate(self.layer_list):
            x = l(x, mask)
        print(x.shape)
        x = self.out(x)
        return torch.softmax(x, dim=-1)
        

x = torch.rand(3, 4, 64)
net = simpleDecoder(64, 8)
mask = (
    torch.tensor([[1, 1, 1, 1], [1, 1, 0, 0], [1, 1, 1, 0]])
    .unsqueeze(1)
    .unsqueeze(2)
    .repeat(1, 8, 4, 1)
)

net(x, mask).shape

torch.Size([3, 8, 4, 4])
tensor([[[[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]]],


        [[[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0]]],


        [[[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 0]]]])

torch.Size([3, 4, 64])

In [25]:
torch.tensor([[1, 1, 1, 1], [1, 1, 0, 0], [1, 1, 1, 0]])

tensor([[1, 1, 1, 1],
        [1, 1, 0, 0],
        [1, 1, 1, 0]])

In [27]:
torch.tensor([[1, 1, 1, 1], [1, 1, 0, 0], [1, 1, 1, 0]]).unsqueeze(1)

tensor([[[1, 1, 1, 1]],

        [[1, 1, 0, 0]],

        [[1, 1, 1, 0]]])

In [30]:
mask.size()

torch.Size([3, 8, 4, 4])

In [50]:
class GroupQueryAttention(nn.Module):
    def __init__(self, dim, head_nums, nums_key_value_head):
        super().__init__()
        self.dim = dim
        self.head_nums = head_nums
        self.head_dim = dim // head_nums
        self.nums_key_value_head = nums_key_value_head
        assert dim % head_nums == 0
        assert head_nums % nums_key_value_head == 0

        self.q_proj = nn.Linear(dim, dim)
        self.k_proj = nn.Linear(dim, nums_key_value_head * self.head_dim)
        self.v_proj = nn.Linear(dim, nums_key_value_head * self.head_dim)
        self.out_proj = nn.Linear(dim, dim)

        self.atten_drop = nn.Dropout(0.1)

    def forward(self, x, mask=None):
        batch, seqlen, _ = x.size()
        q = self.q_proj(x)
        k = self.k_proj(x)
        v = self.v_proj(x)

        q= q.view(batch, seqlen, self.head_nums, self.head_dim).transpose(1, 2)
        k = k.view(batch, seqlen, self.nums_key_value_head, self.head_dim).transpose(1, 2)
        v = v.view(batch, seqlen, self.nums_key_value_head, self.head_dim).transpose(1, 2)

        k = k.repeat_interleave(self.head_nums // self.nums_key_value_head, dim=1)
        v = v.repeat_interleave(self.head_nums // self.nums_key_value_head, dim=1)

        atten_value = q @ k.transpose(-2, -1) / math.sqrt(self.head_dim)
        if mask is not None:
            atten_value = atten_value.masked_fill(mask == 0, float('-inf'))

        atten_weight = torch.softmax(atten_value, dim=-1)
        atten_weight = self.atten_drop(atten_weight)
        atten_weight = atten_weight @ v
        atten_weight = atten_weight.transpose(1, 2).contiguous().view(batch, seqlen, self.dim)
        atten_weight = self.out_proj(atten_weight)
        return atten_weight
    
x = torch.rand(3, 2, 128)
# mask = torch.tensor([[1, 1, 0], [1, 0, 0]])
mask = torch.tensor([[1, 1], [1, 0], [1, 1]])
mask = mask.unsqueeze(1)

print(mask.shape)
print(mask)
mask = mask.repeat(1, 8, 1)

print(mask.shape)
print(mask)

mask = mask.unsqueeze(2)
print(mask.shape)
print(mask)
mask = mask.repeat(1, 1, 2, 1)
print(mask.shape)
net = GroupQueryAttention(128, 8, 2)
res = net(x, mask)
res

torch.Size([3, 1, 2])
tensor([[[1, 1]],

        [[1, 0]],

        [[1, 1]]])
torch.Size([3, 8, 2])
tensor([[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 0],
         [1, 0],
         [1, 0],
         [1, 0],
         [1, 0],
         [1, 0],
         [1, 0],
         [1, 0]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]])
torch.Size([3, 8, 1, 2])
tensor([[[[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]]],


        [[[1, 0]],

         [[1, 0]],

         [[1, 0]],

         [[1, 0]],

         [[1, 0]],

         [[1, 0]],

         [[1, 0]],

         [[1, 0]]],


        [[[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]]]])
torch.Size([3, 8, 2, 2])

tensor([[[ 6.6666e-03, -9.9160e-02,  1.1379e-01,  1.8518e-01, -3.6224e-01,
          -2.9855e-02, -4.7384e-02, -3.5234e-01, -6.2337e-02, -9.0485e-02,
           2.9214e-01,  3.5239e-02,  1.1518e-01,  5.7160e-02, -6.6458e-04,
          -1.5728e-01, -3.1226e-01, -3.0979e-01,  1.6878e-01,  2.9110e-01,
          -4.4592e-02,  1.9372e-01,  1.0063e-01,  4.5153e-02, -3.2966e-02,
          -2.2860e-01,  8.6246e-02, -3.2824e-01,  2.2151e-03,  2.0743e-01,
           1.3626e-01,  4.8235e-02,  6.5652e-02, -1.4964e-01, -2.2121e-01,
          -1.9635e-01,  8.0347e-02, -1.5565e-01,  2.5814e-02,  1.8342e-01,
           1.9436e-01,  8.1992e-02,  1.9683e-01, -1.2243e-01, -4.2661e-02,
           1.4049e-01,  1.2786e-01, -6.8061e-02,  8.5531e-02,  9.6429e-02,
          -1.7822e-01, -1.8240e-01,  1.1726e-01, -3.4998e-02,  1.3788e-01,
          -1.1562e-01, -2.5462e-02, -2.3137e-01,  1.1592e-02,  5.5436e-02,
          -5.3756e-03,  1.0917e-01, -3.1750e-01,  3.4759e-01,  2.1341e-01,
           9.5893e-02,  1.1374e-02, -4.1361e-01, -4.2488e-01,  6.5085e-02,
           1.3247e-02, -1.7409e-02,  3.1080e-01, -4.9466e-01, -1.8018e-01,
           1.8607e-02,  2.3880e-01, -1.1939e-01, -4.7072e-02, -1.9227e-01,
          -6.1695e-02, -7.6438e-02,  5.2550e-02, -1.3200e-01,  1.5632e-01,
          -7.7786e-02,  1.2447e-01, -7.5002e-02,  2.0657e-02, -7.2098e-02,
           1.5892e-02,  3.5244e-01,  5.9499e-02,  5.0029e-01, -1.4812e-01,
          -8.0836e-02, -2.4436e-01, -3.5095e-02,  1.1508e-01,  3.8011e-02,
          -1.3298e-01, -9.2870e-02,  4.3505e-01, -7.7240e-02, -2.1331e-01,
           7.7951e-02,  3.5055e-02, -4.0798e-02, -1.3393e-01,  2.9550e-01,
           7.2377e-02,  2.8395e-01,  1.5422e-02, -1.5291e-01,  6.0609e-02,
           2.1895e-01, -6.8714e-02,  2.5981e-01,  2.2701e-01, -1.2963e-01,
          -4.0337e-02, -1.9682e-01,  3.0086e-01,  3.6414e-01,  3.0986e-01,
           2.8757e-01, -1.6007e-01, -1.8315e-02],
         [-2.3181e-02, -1.5817e-01,  1.9802e-01,  1.8967e-01, -2.9079e-01,
          -3.3482e-02, -5.0570e-02, -3.4294e-01, -1.5645e-01, -1.5611e-01,
           2.9783e-01,  5.4379e-02,  1.2202e-01,  1.0757e-01, -8.2365e-02,
          -1.4997e-01, -3.1290e-01, -3.4882e-01,  1.3261e-01,  3.1812e-01,
          -2.0620e-02,  1.6382e-01,  1.0040e-01,  1.1981e-02, -4.2831e-02,
          -2.1837e-01,  9.2790e-02, -3.8396e-01,  6.9975e-02,  2.0742e-01,
           1.0485e-01,  3.9250e-02,  8.3373e-02, -1.7266e-01, -2.6093e-01,
          -2.0083e-01,  1.1168e-01, -1.5129e-01,  3.1955e-02,  1.9176e-01,
           2.2303e-01,  1.0498e-01,  2.7183e-01, -1.6690e-01, -2.4980e-02,
           1.1634e-01,  1.5860e-01, -9.1183e-02,  5.8595e-02,  4.2378e-02,
          -2.1528e-01, -1.3065e-01,  1.4032e-01, -2.3202e-02,  1.0971e-01,
          -1.1518e-01,  8.3620e-03, -3.1177e-01,  2.0080e-02,  5.5523e-02,
           2.5330e-04,  1.1959e-01, -3.5032e-01,  3.9447e-01,  2.1379e-01,
           1.3388e-01,  6.7297e-02, -4.6914e-01, -4.7004e-01,  4.0619e-02,
           6.7616e-02, -4.1325e-02,  3.4715e-01, -4.5428e-01, -2.1087e-01,
           4.8647e-02,  2.8075e-01, -1.7812e-01, -1.2788e-01, -2.2833e-01,
           3.0422e-02, -9.4644e-02,  5.6022e-03, -1.2898e-01,  1.6353e-01,
          -5.1079e-02,  1.5612e-01, -2.9599e-02,  2.4242e-02, -6.1947e-02,
          -3.6214e-02,  4.0529e-01,  6.5196e-02,  4.8048e-01, -1.4119e-01,
          -3.7522e-02, -3.0451e-01, -6.2420e-02,  1.6577e-01,  8.8486e-02,
          -1.2839e-01, -7.2165e-02,  4.0053e-01, -5.2607e-02, -2.1331e-01,
           3.9845e-02,  6.2783e-02, -6.0345e-02, -2.0070e-01,  3.0975e-01,
           1.0647e-01,  2.0097e-01,  5.1166e-02, -1.9072e-01,  1.0114e-01,
           2.1462e-01, -1.3982e-01,  2.9804e-01,  2.6600e-01, -1.5068e-01,
          -4.5387e-02, -2.1865e-01,  3.2638e-01,  4.2075e-01,  3.4105e-01,
           2.3390e-01, -1.1351e-01, -3.9139e-02]],

        [[-1.6391e-01, -3.7044e-01,  3.6586e-01,  3.1427e-01, -3.6711e-01,
          -9.7720e-02,  4.4474e-02, -7.2748e-01, -2.3803e-02, -2.6857e-01,
           1.1614e-01, -1.1254e-01,  1.7069e-01, -8.9498e-02, -2.1091e-01,
          -3.2840e-01, -7.6239e-02, -2.9967e-01,  4.2316e-02,  2.2930e-01,
           1.1957e-01,  5.7703e-01,  9.4411e-02,  3.4860e-02, -1.7732e-01,
          -4.5289e-01, -1.0194e-01, -3.5753e-01,  3.3873e-01,  5.8431e-02,
           3.6019e-01, -1.7075e-02,  1.2222e-01,  8.8958e-02, -1.4552e-01,
          -5.0944e-02,  1.5213e-01, -6.9300e-03,  1.7811e-01,  3.2124e-01,
           2.5210e-01,  2.7623e-01,  1.3691e-01, -1.8300e-01, -9.1393e-02,
           1.3467e-01,  7.7303e-03,  9.3274e-02, -5.0351e-02, -2.3703e-02,
          -1.4231e-01, -1.6153e-01, -1.3015e-02,  3.7294e-02,  1.2401e-01,
           4.4395e-02, -4.0592e-02, -5.5867e-02,  4.4814e-02,  3.6029e-01,
          -1.7625e-02,  7.3635e-02, -1.7973e-01,  3.8618e-01,  1.4496e-01,
          -1.4179e-01,  1.6091e-01, -3.7535e-01, -2.1578e-01, -7.4227e-02,
          -1.7433e-01, -5.4109e-02,  5.8417e-01, -5.5880e-01, -3.8760e-01,
           1.1472e-01,  1.1955e-01, -9.8578e-02, -1.0084e-01, -2.9995e-01,
           4.4009e-02,  1.8119e-01, -1.9032e-01, -1.0951e-01,  2.5045e-01,
           2.1073e-02,  3.1002e-01, -5.6193e-02,  5.6823e-02, -1.9288e-01,
          -1.3142e-01,  1.9764e-01,  1.9047e-01,  3.7567e-01, -3.0017e-01,
           2.8761e-01, -8.7241e-02, -1.3336e-01,  5.8901e-02,  2.9034e-01,
          -1.7343e-01,  1.0361e-01,  1.4184e-01, -9.4055e-02, -1.0100e-01,
           2.8613e-01, -7.2788e-02, -2.1962e-01, -2.4021e-01,  4.1493e-01,
           2.1894e-03,  2.0483e-01,  3.1162e-01, -2.2774e-01,  4.2128e-01,
           4.0135e-01,  6.4866e-03,  3.5067e-01, -8.4322e-02, -3.0884e-01,
          -1.0865e-01, -2.3045e-01,  3.0841e-01,  4.2252e-01,  3.6193e-01,
           5.2615e-01,  8.5110e-02, -2.6725e-02],
         [-1.6391e-01, -3.7044e-01,  3.6586e-01,  3.1427e-01, -3.6711e-01,
          -9.7720e-02,  4.4474e-02, -7.2748e-01, -2.3803e-02, -2.6857e-01,
           1.1614e-01, -1.1254e-01,  1.7069e-01, -8.9498e-02, -2.1091e-01,
          -3.2840e-01, -7.6239e-02, -2.9967e-01,  4.2316e-02,  2.2930e-01,
           1.1957e-01,  5.7703e-01,  9.4411e-02,  3.4860e-02, -1.7732e-01,
          -4.5289e-01, -1.0194e-01, -3.5753e-01,  3.3873e-01,  5.8431e-02,
           3.6019e-01, -1.7075e-02,  1.2222e-01,  8.8958e-02, -1.4552e-01,
          -5.0944e-02,  1.5213e-01, -6.9300e-03,  1.7811e-01,  3.2124e-01,
           2.5210e-01,  2.7623e-01,  1.3691e-01, -1.8300e-01, -9.1393e-02,
           1.3467e-01,  7.7303e-03,  9.3274e-02, -5.0351e-02, -2.3703e-02,
          -1.4231e-01, -1.6153e-01, -1.3015e-02,  3.7294e-02,  1.2401e-01,
           4.4395e-02, -4.0592e-02, -5.5867e-02,  4.4814e-02,  3.6029e-01,
          -1.7625e-02,  7.3635e-02, -1.7973e-01,  3.8618e-01,  1.4496e-01,
          -1.4179e-01,  1.6091e-01, -3.7535e-01, -2.1578e-01, -7.4227e-02,
          -1.7433e-01, -5.4109e-02,  5.8417e-01, -5.5880e-01, -3.8760e-01,
           1.1472e-01,  1.1955e-01, -9.8578e-02, -1.0084e-01, -2.9995e-01,
           4.4009e-02,  1.8119e-01, -1.9032e-01, -1.0951e-01,  2.5045e-01,
           2.1073e-02,  3.1002e-01, -5.6193e-02,  5.6823e-02, -1.9288e-01,
          -1.3142e-01,  1.9764e-01,  1.9047e-01,  3.7567e-01, -3.0017e-01,
           2.8761e-01, -8.7241e-02, -1.3336e-01,  5.8901e-02,  2.9034e-01,
          -1.7343e-01,  1.0361e-01,  1.4184e-01, -9.4055e-02, -1.0100e-01,
           2.8613e-01, -7.2788e-02, -2.1962e-01, -2.4021e-01,  4.1493e-01,
           2.1894e-03,  2.0483e-01,  3.1162e-01, -2.2774e-01,  4.2128e-01,
           4.0135e-01,  6.4866e-03,  3.5067e-01, -8.4322e-02, -3.0884e-01,
          -1.0865e-01, -2.3045e-01,  3.0841e-01,  4.2252e-01,  3.6193e-01,
           5.2615e-01,  8.5110e-02, -2.6725e-02]],

        [[-2.4084e-01, -2.7680e-01,  1.9965e-01,  1.4178e-01, -3.4754e-01,
          -7.8835e-02,  1.1469e-02, -2.7639e-01, -4.0972e-02, -9.1041e-02,
           2.1406e-01, -2.2251e-02,  5.5813e-02, -3.2587e-02, -1.8146e-02,
          -3.6141e-01, -9.2600e-02, -3.5565e-01,  1.0858e-04,  2.6270e-01,
           5.5755e-02,  3.6231e-01,  1.7066e-01, -1.2074e-01, -1.1803e-02,
          -1.9519e-01, -5.1856e-02, -3.0895e-01,  1.8568e-01,  7.9099e-02,
           2.5914e-01, -6.5535e-03,  1.4724e-01,  1.0298e-03, -8.8909e-02,
          -1.7973e-01,  4.9746e-02, -7.9741e-03,  1.1697e-01,  2.1338e-01,
           1.2253e-01,  2.7014e-01,  1.6621e-01, -1.5736e-01, -1.6154e-01,
           1.3111e-01,  3.8413e-02, -9.0179e-02, -8.2538e-02,  3.3631e-02,
          -2.3032e-01, -3.7083e-02, -1.5679e-03,  1.4687e-02,  5.9550e-02,
          -2.1721e-02, -2.7763e-02, -2.0144e-01, -5.3578e-03,  2.8767e-01,
          -1.7792e-01,  1.7553e-01, -2.7551e-01,  4.0949e-01,  1.0193e-01,
          -3.4096e-02,  1.8851e-01, -2.5097e-01, -2.3743e-01, -9.1916e-02,
           1.1570e-01, -4.3681e-02,  3.8355e-01, -3.4680e-01, -2.2967e-01,
           1.5365e-01,  2.7895e-02, -1.4004e-01, -2.3686e-01, -3.4726e-01,
           1.2248e-01,  1.7180e-02, -9.4893e-02, -2.8124e-01,  8.9956e-02,
           4.9092e-02,  2.3172e-01,  5.9588e-02, -6.1533e-02, -9.8873e-02,
          -1.3382e-01,  1.7621e-01,  1.4270e-01,  3.3173e-01, -1.2154e-01,
           1.1496e-01, -1.9625e-01, -1.1953e-01,  1.5816e-01,  2.4936e-01,
          -1.0146e-01,  3.8900e-02,  1.6316e-01, -2.2681e-02, -1.6827e-01,
           1.7621e-01, -1.4384e-01, -1.2490e-01, -2.2306e-01,  4.5071e-01,
          -1.2357e-02,  1.7225e-02,  1.7874e-01, -2.2865e-01,  2.9421e-01,
           3.0032e-01, -1.7998e-02,  3.3391e-01,  1.0763e-01, -2.4620e-01,
          -1.0195e-01, -2.1050e-01,  2.7816e-01,  3.8914e-01,  2.8085e-01,
           3.3911e-01,  1.0498e-01, -4.7225e-02],
         [-2.0210e-01, -2.8253e-01,  2.6501e-01,  1.6169e-01, -3.4113e-01,
          -7.2509e-02,  7.1101e-03, -3.5463e-01, -5.6300e-02, -1.5950e-01,
           2.1407e-01, -9.9278e-02,  6.2199e-02, -4.2071e-02, -2.5809e-02,
          -3.3043e-01, -1.2907e-01, -3.7628e-01,  1.9166e-02,  3.2697e-01,
           8.7154e-02,  3.9551e-01,  1.2808e-01, -1.1362e-01, -4.8095e-02,
          -2.6269e-01,  3.2105e-02, -2.7197e-01,  1.8430e-01,  6.4012e-02,
           2.8504e-01,  1.0879e-02,  1.7776e-01, -2.2049e-03, -7.5551e-02,
          -1.9561e-01,  1.0232e-01, -1.8423e-02,  1.3538e-01,  2.3961e-01,
           1.6133e-01,  3.0735e-01,  1.9175e-01, -1.4689e-01, -1.9607e-01,
           9.6749e-02,  4.3633e-02, -9.2134e-02, -5.4961e-02,  2.6900e-02,
          -2.7385e-01, -1.9545e-01,  9.7942e-03, -9.6460e-03,  1.0305e-01,
           5.7273e-02, -6.1738e-02, -1.9591e-01,  3.1497e-02,  2.6558e-01,
          -1.1531e-01,  2.0400e-01, -2.8250e-01,  4.1707e-01,  1.2267e-01,
          -8.5643e-03,  1.6025e-01, -2.6715e-01, -2.4740e-01, -5.6465e-02,
           6.7144e-02, -9.0091e-02,  3.4723e-01, -4.1011e-01, -3.4218e-01,
           1.3459e-01,  8.9376e-02, -1.1438e-01, -2.0933e-01, -3.1669e-01,
           8.8121e-02,  1.0957e-02, -9.2082e-02, -2.2851e-01,  1.7511e-01,
           6.0987e-02,  3.3608e-01,  3.3876e-02,  1.4807e-02, -5.4255e-02,
          -9.8332e-02,  1.8161e-01,  1.2533e-01,  3.6323e-01, -1.3229e-01,
           1.2615e-01, -2.4239e-01, -1.2263e-01,  1.1228e-01,  2.5670e-01,
          -1.3400e-01,  7.7918e-03,  2.6902e-01, -1.5481e-03, -1.7628e-01,
           1.5614e-01, -1.1665e-01, -9.0850e-02, -2.3926e-01,  4.6221e-01,
          -9.0368e-02,  1.1815e-01,  1.7565e-01, -1.7788e-01,  3.1808e-01,
           3.1095e-01,  7.0711e-02,  3.2222e-01,  4.4791e-02, -2.6466e-01,
          -1.0736e-01, -2.1379e-01,  3.5004e-01,  3.4870e-01,  3.3323e-01,
           3.8200e-01,  1.0464e-01, -5.6350e-02]]], grad_fn=<ViewBackward0>)